import mongoose from "mongoose";


const assessmentSchema = new mongoose.Schema({
   IQ: {
      type: {
         _id: false,
         t: Number,
         options: {
            _id: false,
            i1: { o: Number, p: Number, _id: false },
            i2: { o: Number, p: Number, _id: false },
            i3: { o: Number, p: Number, _id: false },
            i4: { o: Number, p: Number, _id: false },
            i5: { o: Number, p: Number, _id: false },
            i6: { o: Number, p: Number, _id: false },
            i7: { o: Number, p: Number, _id: false },
            i8: { o: Number, p: Number, _id: false },
            i9: { o: Number, p: Number, _id: false },
            i10: { o: Number, p: Number, _id: false },
            i11: { o: Number, p: Number, _id: false },
            i12: { o: Number, p: Number, _id: false },
            i13: { o: Number, p: Number, _id: false },
            i14: { o: Number, p: Number, _id: false },
            i15: { o: Number, p: Number, _id: false },
            i16: { o: Number, p: Number, _id: false },
            i17: { o: Number, p: Number, _id: false },
            i18: { o: Number, p: Number, _id: false },
            i19: { o: Number, p: Number, _id: false },
            i20: { o: Number, p: Number, _id: false },
            i21: { o: Number, p: Number, _id: false },
            i22: { o: Number, p: Number, _id: false },
            i23: { o: Number, p: Number, _id: false },
            i24: { o: Number, p: Number, _id: false },
            i25: { o: Number, p: Number, _id: false },
            i26: { o: Number, p: Number, _id: false },
            i27: { o: Number, p: Number, _id: false },
            i28: { o: Number, p: Number, _id: false },
            i29: { o: Number, p: Number, _id: false },
            i30: { o: Number, p: Number, _id: false },
            i31: { o: Number, p: Number, _id: false },
            i32: { o: Number, p: Number, _id: false },
            i33: { o: Number, p: Number, _id: false },
            i34: { o: Number, p: Number, _id: false },
            i35: { o: Number, p: Number, _id: false },
            i36: { o: Number, p: Number, _id: false },
            i37: { o: Number, p: Number, _id: false },
            i38: { o: Number, p: Number, _id: false },
            i39: { o: Number, p: Number, _id: false },
            i40: { o: Number, p: Number, _id: false },
            i41: { o: Number, p: Number, _id: false },
            i42: { o: Number, p: Number, _id: false },
            i43: { o: Number, p: Number, _id: false },
            i44: { o: Number, p: Number, _id: false },
            i45: { o: Number, p: Number, _id: false },
            i46: { o: Number, p: Number, _id: false },
            i47: { o: Number, p: Number, _id: false },
            i48: { o: Number, p: Number, _id: false },
            i49: { o: Number, p: Number, _id: false },
            i50: { o: Number, p: Number, _id: false },
            i51: { o: Number, p: Number, _id: false },
            i52: { o: Number, p: Number, _id: false },
            i53: { o: Number, p: Number, _id: false },
            i54: { o: Number, p: Number, _id: false },
            i55: { o: Number, p: Number, _id: false },
            i56: { o: Number, p: Number, _id: false },
            i57: { o: Number, p: Number, _id: false },
            i58: { o: Number, p: Number, _id: false },
            i59: { o: Number, p: Number, _id: false },
            i60: { o: Number, p: Number, _id: false },
         }
      }
   },
   SH: {
      type: {
         t: Number,
         rh: Number,
         eh: Number,
         options: {
            i1: { o: Number, p: Number, _id: false },
            i2: { o: Number, p: Number, _id: false },
            i3: { o: Number, p: Number, _id: false },
            i4: { o: Number, p: Number, _id: false },
            i5: { o: Number, p: Number, _id: false },
            i6: { o: Number, p: Number, _id: false },
            i7: { o: Number, p: Number, _id: false },
            i8: { o: Number, p: Number, _id: false },
            i9: { o: Number, p: Number, _id: false },
            i10: { o: Number, p: Number, _id: false },
            i11: { o: Number, p: Number, _id: false },
            i12: { o: Number, p: Number, _id: false },
            i13: { o: Number, p: Number, _id: false },
            i14: { o: Number, p: Number, _id: false },
            i15: { o: Number, p: Number, _id: false },
            i16: { o: Number, p: Number, _id: false },
            i17: { o: Number, p: Number, _id: false },
            i18: { o: Number, p: Number, _id: false },
            i19: { o: Number, p: Number, _id: false },
            i20: { o: Number, p: Number, _id: false },
         }
      }
   },
   PF: {
      type: {
         _id: false,
         of: Number,
         cf: Number,
         ef: Number,
         af: Number,
         nf: Number,
         options: {
            _id: false,
            i1: { o: Number, p: Number, _id: false },
            i2: { o: Number, p: Number, _id: false },
            i3: { o: Number, p: Number, _id: false },
            i4: { o: Number, p: Number, _id: false },
            i5: { o: Number, p: Number, _id: false },
            i6: { o: Number, p: Number, _id: false },
            i7: { o: Number, p: Number, _id: false },
            i8: { o: Number, p: Number, _id: false },
            i9: { o: Number, p: Number, _id: false },
            i10: { o: Number, p: Number, _id: false },
            i11: { o: Number, p: Number, _id: false },
            i12: { o: Number, p: Number, _id: false },
            i13: { o: Number, p: Number, _id: false },
            i14: { o: Number, p: Number, _id: false },
            i15: { o: Number, p: Number, _id: false },
            i16: { o: Number, p: Number, _id: false },
            i17: { o: Number, p: Number, _id: false },
            i18: { o: Number, p: Number, _id: false },
            i19: { o: Number, p: Number, _id: false },
            i20: { o: Number, p: Number, _id: false },
            i21: { o: Number, p: Number, _id: false },
            i22: { o: Number, p: Number, _id: false },
            i23: { o: Number, p: Number, _id: false },
            i24: { o: Number, p: Number, _id: false },
            i25: { o: Number, p: Number, _id: false },
            i26: { o: Number, p: Number, _id: false },
            i27: { o: Number, p: Number, _id: false },
            i28: { o: Number, p: Number, _id: false },
            i29: { o: Number, p: Number, _id: false },
            i30: { o: Number, p: Number, _id: false },
            i31: { o: Number, p: Number, _id: false },
            i32: { o: Number, p: Number, _id: false },
            i33: { o: Number, p: Number, _id: false },
            i34: { o: Number, p: Number, _id: false },
            i35: { o: Number, p: Number, _id: false },
            i36: { o: Number, p: Number, _id: false },
            i37: { o: Number, p: Number, _id: false },
            i38: { o: Number, p: Number, _id: false },
            i39: { o: Number, p: Number, _id: false },
            i40: { o: Number, p: Number, _id: false },
            i41: { o: Number, p: Number, _id: false },
            i42: { o: Number, p: Number, _id: false },
            i43: { o: Number, p: Number, _id: false },
            i44: { o: Number, p: Number, _id: false },
            i45: { o: Number, p: Number, _id: false },
            i46: { o: Number, p: Number, _id: false },
            i47: { o: Number, p: Number, _id: false },
            i48: { o: Number, p: Number, _id: false },
            i49: { o: Number, p: Number, _id: false },
            i50: { o: Number, p: Number, _id: false },
            i51: { o: Number, p: Number, _id: false },
            i52: { o: Number, p: Number, _id: false },
            i53: { o: Number, p: Number, _id: false },
            i54: { o: Number, p: Number, _id: false },
            i55: { o: Number, p: Number, _id: false },
            i56: { o: Number, p: Number, _id: false },
            i57: { o: Number, p: Number, _id: false },
            i58: { o: Number, p: Number, _id: false },
            i59: { o: Number, p: Number, _id: false },
            i60: { o: Number, p: Number, _id: false },
         }
      }
   },
   schoolName: {
      type: String,
      required: true
   },
   grade: {
      type: String,
      required: true
   },
   birthday: {
      type: {
         _id: false,
         day: String,
         month: String,
         year: String,
      }
   }
}, {
   timestamps: true
})

const Assessment = mongoose.models.Assessment || mongoose.model('Assessment', assessmentSchema)

export default Assessment